step8:deploy infra

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,6 +1,31 @@
 version: 2.1
 orbs:
   slack: circleci/slack@4.12.5
+
+commands:
+  destroy-environment:
+    description: Destroy back-end and front-end CloudFormation stacks given a workflow ID.
+    parameters:
+      workflow-id:
+        description: Workflow ID to identify the CloudFormation stacks.
+        type: string
+        default: "${CIRCLE_WORKFLOW_ID:0:7}"  # Default to first 7 characters of workflow ID
+    steps:
+      - run:
+          name: Destroy environments
+          when: on_fail
+          command: |
+
+            # Delete backend stack if it was created
+            aws cloudformation delete-stack --stack-name udapeople-backend-<<parameters.workflow-id>>
+            
+            # Delete frontend stack if it was created
+            aws cloudformation delete-stack --stack-name udapeople-frontend-<<parameters.workflow-id>>
+            
+            # Exit with a failure status
+            exit 1
+
+
 jobs:
   build-frontend:
     docker:
@@ -100,6 +125,42 @@ jobs:
             npm audit fix --force
             npm audit --audit-level=critical
 
+  deploy-infrastructure:
+    docker:
+      - image: amazon/aws-cli  # Replace with the Docker image that supports AWS CLI
+    steps:
+      - checkout  # Checkout code from Git
+      - run:
+          name: Ensure back-end infrastructure exists
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/backend.yml \
+              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
+              --tags project=udapeople
+      - run:
+          name: Ensure front-end infrastructure exists
+          command: |
+            aws cloudformation deploy \
+              --template-file .circleci/files/frontend.yml \
+              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
+              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"  \
+              --tags project=udapeople
+      - run:
+          name: Add back-end IP to Ansible inventory
+          command: |
+            # Fetch EC2 instance IP
+            INSTANCE_IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=backend-*" --query "Reservations[].Instances[].PublicIpAddress" --output text)
+            echo "[web]" > ~/workspace/amit-cdond-c3-project/.circleci/ansible/inventory.txt
+            echo "$INSTANCE_IP" >> ~/workspace/amit-cdond-c3-project/.circleci/ansible/inventory.txt
+      - persist_to_workspace:
+          root: ~/
+          paths:
+            - /workspace/amit-cdond-c3-project/.circleci/ansible/inventory.txt
+
+      # Destroy environment on failure
+      - destroy-environment:
+          workflow-id: ${CIRCLE_WORKFLOW_ID:0:7}
 workflows:
   default:
     jobs:
@@ -114,3 +175,5 @@ workflows:
           requires: [build-backend]
       - scan-frontend:
           requires: [build-frontend]
+      - deploy-infrastructure:
+          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
